IMPLY-3713 added processing module test

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -43,12 +43,6 @@ def MVN_OPTS         = "export MAVEN_OPTS=\"-Xms4g -Xmx8g -XX:MaxDirectMemorySiz
 def MAVEN_SKIP       = "-Danimal.sniffer.skip=true -Dcheckstyle.skip=true -Ddruid.console.skip=true -Denforcer.skip=true -Dforbiddenapis.skip=true -Dmaven.javadoc.skip=true -Dpmd.skip=true -Dspotbugs.skip=true"
 def MAVEN_SKIP_TESTS = "-DskipTests -Djacoco.skip=true"
 
-// def GENERATE_LICENSE_DOCKERFILE = """\
-// ARG JDK
-// FROM maven:3.6.3-\${JDK}
-// RUN apt-get update -y && apt-get install python3 python3-pip python3-setuptools -y
-// RUN pip3 install wheel pyyaml
-// """
 
 def buildGenerateLicenseImage = { jdkVersion ->
     writeFile file: "${env.WORKSPACE}@tmp/Dockerfile", text: """\
@@ -60,6 +54,105 @@ RUN pip3 install wheel pyyaml
     return docker.build(
         "maven:jdk-${jdkVersion}-${env.STAGE_NAME.replaceAll(~/[^a-z0-9]/,'')}${env.BUILD_ID}",
         "${env.WORKSPACE}@tmp")
+}
+
+def withGitCredentials = { body ->
+    withCredentials([
+        usernamePassword(
+            credentialsId: scm.userRemoteConfigs.getCredentialsId(),
+            passwordVariable: 'GIT_PASSWORD',
+            usernameVariable: 'GIT_USERNAME')
+        ]) {
+            body()
+    }
+}
+
+def buildImageWithNode = { jdkVersion ->
+    writeFile file: "${env.WORKSPACE}@tmp/Dockerfile", text: """\
+FROM maven:3.6.3-jdk-${jdkVersion}
+RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
+    apt-get install -y nodejs
+"""
+
+    return docker.build(
+        "maven:jdk-${jdkVersion}-${env.STAGE_NAME.replaceAll(~/[^a-z0-9]/,'')}${env.BUILD_ID}",
+        "${env.WORKSPACE}@tmp")
+}
+
+
+def testProcessingModule = { stageName, jdkVersion, envMap
+    stage(stageName) {
+        lightweightNode {
+            withArtifactorySettings { settingsPath ->
+                buildImageWithNode(jdkVersion).inside(
+                    withGitCredentials {}
+                    "--memory=8g --memory-reservation=4g -v ${settingsPath}:/tmp/.m2/settings.xml -e HOME=/tmp") {
+                    checkout scm
+                    withGitCredentials {
+                        withEnv(envMap) {
+                            sh script: """#!/bin/bash -x
+
+                                mkdir -p /tmp/bin
+                                /bin/echo -e "#!/bin/sh\\ncase \"\\\$1\" in\\nUsername*) echo \"\\\$GIT_USERNAME\" ;;\\nPassword*) echo \"\\\$GIT_PASSWORD\" ;;\\nesac\\n" | tee -a /tmp/bin/askpass
+                                chmod u+x /tmp/bin/askpass
+                                /bin/echo -e "#!/bin/sh\\n\"\\\$@\" || \"\\\$@\" || \"\\\$@\"" | tee -a /tmp/bin/retry3times
+                                chmod u+x /tmp/bin/retry3times
+                                export PATH=/tmp/bin:\$PATH
+
+                                unset _JAVA_OPTIONS
+
+                                MAVEN_OPTS='-Xmx800m' ${MVN} test -pl \${MAVEN_PROJECTS} \
+                                ${MAVEN_SKIP} -Dremoteresources.skip=true -Ddruid.generic.useDefaultValueForNull=\${DRUID_USE_DEFAULT_VALUE_FOR_NULL}
+
+                                sh -c "dmesg | egrep -i '(oom|out of memory|kill process|killed).*' -C 1 || exit 0"
+                                free -m
+                                ${MVN} -pl \${MAVEN_PROJECTS} jacoco:report
+
+                                export TARGET_BRANCH_NAME=\${CHANGE_TARGET:-${env.BRANCH_NAME}}
+                                git remote set-branches --add origin \${BRANCH_NAME:-master} && git fetch
+                                all_files="\$(git diff --name-only origin/\${TARGET_BRANCH_NAME}...HEAD | grep "\\.java\$" || [[ \$? == 1 ]])"
+
+                                for f in \${all_files} do
+                                    echo \$f
+                                done
+
+                                if [[ "\${MAVEN_PROJECTS}" = \\!* ]]; then
+                                  regex="\${MAVEN_PROJECTS:1}";
+                                  regex="^\${regex//,\\!/\\\\|^}";
+                                  project_files="\$(echo "\${all_files}" | grep -v "\${regex}" || [[ \$? == 1 ]])";
+                                else
+                                  regex="^\${MAVEN_PROJECTS//,/\\\\|^}";
+                                  project_files="\$(echo "\${all_files}" | grep "\${regex}" || [[ \$? == 1 ]])";
+                                fi
+
+                                for f in \${project_files} do
+                                    echo \$f
+                                done
+
+                                if [ -n "\${project_files}" ]; then
+                                    retry3times npm install @connectis/diff-test-coverage@1.5.3 && \
+                                    git diff origin/\${TARGET_BRANCH_NAME}...HEAD -- \${project_files} | \
+                                    node_modules/.bin/diff-test-coverage \
+                                      --coverage "**/target/site/jacoco/jacoco.xml" \
+                                      --type jacoco \
+                                      --line-coverage 50 \
+                                      --branch-coverage 50 \
+                                      --function-coverage 0 \
+                                      --log-template "coverage-lines-complete" \
+                                      --log-template "coverage-files-complete" \
+                                      --log-template "totals-complete" \
+                                      --log-template "errors" \
+                                      -- || \
+                                    { printf "\\n\\n****FAILED****\\nDiff code coverage check failed. To view coverage report, run 'mvn clean test jacoco:report' and open 'target/site/jacoco/index.html'\\nFor more details on how to run code coverage locally, follow instructions here - https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md#running-code-coverage-locally\\n\\n" && false; }
+                                fi
+                            """
+                        }
+                    }
+
+                }
+            }
+        }
+    }
 }
 
 def packagingCheck = { jdkVersion ->
@@ -78,6 +171,7 @@ def packagingCheck = { jdkVersion ->
         }
     }
 }
+
 
 stage("Maven install") {
     lightweightNode {
@@ -215,7 +309,14 @@ stage("Checks") {
     },
     "(openjdk11) packaging check": {
         packagingCheck(11)
-    }
+    },
+    "(openjdk8) processing module test" {
+        testProcessingModule("(openjdk8) processing module test", 8, [MAVEN_PROJECTS:"processing", DRUID_USE_DEFAULT_VALUE_FOR_NULL:"true"])
+    },
+    "(openjdk11) processing module test" {
+        testProcessingModule("(openjdk8) processing module test", 11, [MAVEN_PROJECTS:"processing", DRUID_USE_DEFAULT_VALUE_FOR_NULL:"true"])
+    },
+
 }
 
 
